### ISSUE TITLE
Processor  for deleting fields

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/datapackage-pipelines#102]
As a dpp user, I want to be able to pre-define unnecessary columns for my data, so that after running `dpp run xxx`  output data does not have those columns 

## Acceptance Criteria

* [x] able to delete column with `dpp`

## Tasks 

* [x] write spec
* [x] write tests
* [x] add `remove_fields` processor to common processors
* [x] update README

## Analysis 

Spec: 

```
run: delete_fields
parameters:
  resources: resource_name
  columns:
    - column_name1
    - column_name2
```
