### ISSUE TITLE
Unpivot  tabular data

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/datapackage-pipelines#108]
As a dpp user, I want to unpivot or transpose my tabular data so that there's only one record per row

As a dpp user, I have data that has dates as  column names and I want to "unpivot" and have nice time series data so that I can easily reuse it for plotting graphs

Example:

```
# Pivoted data
country  	2005	2006	2007	
Afghanistan	46.6	46.9	47.2	
Albania	        76.1	76.3	76.5	
...

# Unpivoted data
country      year  average_age
Afghanistan  2005  46.6
Afghanistan  2006  46.9
Afghanistan  2007  47.2
Albania      2005  76.1
Albania      2006  76.3
Albania      2007  76.5
...
```

## Acceptance criteria

* [ ] Able to normalize my pivoted data
* [ ] `dpp run un-pivot-processor` provides valid datapackage 
* [ ] Able to pre define the name of columns to insert values

## Tasks

* [x] Do analysis
* [x] Prepare Spec
* [x] Failing Tests for processor
* [x] Create unpivot processor
* [ ] Passing test
* [ ] update REAMDE

## Analysis 

Example Spec for given data:
```
# data
country,2015 income,2015 expenses,2016 income,2016 expenses
xxx,20000,15000,30000,30000
...

# spec
- run: unpivot
  parameters:
    resources: (same as always)
    extraKeyFields:
      -
        name: year
        type: integer
      -
        name: direction
        name: string
    extraValueField:
        name: amount
        type: number
    unpivot:
      - 
        name: 2015 incomes
        keys:
          year: 2015
          direction: In
      - 
        name: 2015 expenses
        keys:
          year: 2015
          direction: Out
      - 
        name: 2016 incomes
        keys:
          year: 2016
          direction: In
      - 
        name: 2016 expenses
        keys:
          year: 2015
          direction: Out
      # or regex 
      -
        name: ([0-9]{4}) (\w+)
        keys:
          year: \1
          direction: \2
```
