### ISSUE TITLE
Small bug in a documentation

### ISSUE THREAD

**Issue by AcckiyGerman** [frictionlessdata/datapackage-pipelines#116]
## Tasks
* [ ] fix docs

## Analysis
There is a example about unpivot feature:
```yaml
unpivot:
    -
      name: ([0-9]{4}) (\\w+)  # regex for original column
      keys:
        year: \\1  # First member of group from above
        direction: \\2  # Second member of group from above
```
I'm not sure why is here double backslash `\\1` in the readme, but when I use `dpp` in a pipeline processor with this example I got `ERROR :Failed to cast row: Field "year" can't cast value "\1" for type "year" with format "default"`.   With `\1` everything is ok.

Please, somebody ping me to ensure that there is no special reasons to use double backslash `\\` and I'll fix the doc.
