### ISSUE TITLE
Albanian example in README doesn't work

### ISSUE THREAD

**Issue by Vanuan** [frictionlessdata/datapackage-pipelines#18]
So, I've tried to run Albanian example pipeline specified in README.

```
version: '2'
services:
  pipeline:
    build: .
    command: sh -c "cd /src && pwd && dpp"
    ports:
      - 5000:5000
    volumes:
      - ./:/src
```

```
pipeline_1  | Available Pipelines:
pipeline_1  | - ./albanian-treasury (E)
pipeline_1  | 	Unresolved processor: Couldn't resolve model at /src
```

Which processor I need to install additionally?
