### ISSUE TITLE
Ability to set environment variables for a pipeline

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-pipelines#181]
# Overview

Recently, I've added support for `TABLESCHEMA_PRESERVE_MISSING_VALUES` env var to `tableschema-py` - https://github.com/frictionlessdata/tableschema-py#experimental - which can be useful for some use cases.

I propose we have a standard way to declare environment variables for a pipeline as it implemented for many other declarative formats like `docker-compose.yml`, `travis.yml`, etc

So we can have something like this:

```yml
temporal:
  title: temporal
  description: "temporal format"
  enviroment:
    DEBUG: True
  pipeline:

  - run: load
    parameters:
      from: 'temporal.csv'
      override_fields:
        date:
          outputFormat: '%m/%d/%Y'

  - run: dump_to_path
    parameters:
      out-path: 'output'
      pretty-descriptor: true
      temporal_format_property: outputFormat
```

**Comment by roll** [comment]
@akariv 
WDYT? Does it make sense?

**Comment by akariv** [comment]
I have to admit I don't necessarily see the use case here that is somewhere in between passing parameters to a processor and using actual environment variables.

passing common parameters to all processors might be achieved more elegantly by creating 'global parameters' which are then passed to all processors, updating the per-processor parameters (elegance is debatable, of course 😄 ).

e.g
```yaml
temporal:
  title: temporal
  description: "temporal format"
    parameters:
      debug: True
  pipeline:
  - run: load
    parameters:
      from: 'temporal.csv'
      override_fields:
        date:
          outputFormat: '%m/%d/%Y'

  - run: dump_to_path
    parameters:
      out-path: 'output'
      pretty-descriptor: true
      temporal_format_property: outputFormat
```

Is there any other use case here other than controlling the FD libraries behavior (I'm honestly asking here)?
