### ISSUE TITLE
Loading file with capital letters

### ISSUE THREAD

**Issue by gperonato** [frictionlessdata/datapackage-pipelines#197]
When loading a file containing capital letters, an error is raised, as there is a validation error. I have tried to correct this with `update_package `and `update_resource`, but the same error occurs when the first processor is called.
Is there a way to change this behavior? I cannot change the name of an online dataset.
The same dataset does not cause any error in `dataflows`.
Thanks,
Giuseppe

Python 3.82
MacOs 10.15.7

**Comment by akariv** [comment]
Hey Giuseppe - do you mean that the file name contains uppercase letters,
or that the uppercase letters are in a different location?
If possible, could you share your pipeline-spec file and some sample of
your source file?

**Comment by gperonato** [comment]
Hi Adam,
yes sorry, I meant uppercase letters, which do not match the validation `'^([-a-z0-9._/])+$'`.
Here is my pipeline-spec with the link to the source file:
```
JRC_GEOPP_DB_3:
  pipeline:
  - run: load
    parameters:
      from: http://cidportal.jrc.ec.europa.eu/ftp/jrc-opendata/JRCOD/RES-DATA/10001/LATEST/JRC-GEOPP-DB.csv
  - run: dump.to_path
    parameters:
      out-path: JRC_GEOPP_DB
```
Thank you,
Giuseppe
