### ISSUE TITLE
Examples in README are mixing tabs and spaces

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-pipelines#73]
For example, see https://github.com/frictionlessdata/datapackage-pipelines/blob/054db2faa0e768104ac43fd070cf3cc2e17ef69f/README.md#add_resource. The YAML example is:

```yaml
- run: add_resource
  parameters: 
    url: http://example.com/my-excel-file.xlsx
    sheet: 1
    headers: 2
- run: add_resource
  parameters:
    url: http://example.com/my-csv-file.csv
	encoding: "iso-8859-2"
```

Notice the red highlight before `encoding`. That's a TAB. I'm not sure which level the `encoding` should be in, so I couldn't send a PR, but there are a few examples like this in the README.
