### ISSUE TITLE
Encoding problems when trying to dump.to_zip the remote dataset with non-tabular resource

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/datapackage-pipelines#89]
If you try and `dump.to_zip` the remote dataset with a non-tabular resource with dpp, it will zip successfully, but if you try and open zipped resource it has encoding problems. Reproduce:
* Run the following pipeline
```
remote:
  pipeline:
    -
      run: load_resource
      parameters:
        resource: 'vix-daily_json'
        url: "https://pkgstore-testing.datahub.io/core/finance-vix:vix-daily_json/datapackage.json"
        stream: False
    -
      run: dump.to_zip
      parameters:
          out-file: remote.zip
          force-format: False
          handle-non-tabular: True
```
* Unzip
* open `data/vix-daily_json.json`

*Note: emphasizing **remote** here as if you try and download [datapackage.json](https://pkgstore-testing.datahub.io/core/finance-vix:vix-daily_json/datapackage.json) and [data/vix-daily_json.json](https://pkgstore-testing.datahub.io/core/finance-vix:vix-daily_json/data/vix-daily_json.json) locally and  zip - it works fine*

See detailed debug here https://github.com/datahq/assembler/issues/53#issuecomment-336800232
